[project]
name = "servicenow-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maru Karthik Reddy", email = "karthikreddy.maru@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.2",
    "langchain-openai>=1.6.1",
    "requests>=2.34.2",
]

[project.scripts]
servicenow-ai = "servicenow_ai:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
